### ISSUE TITLE
Example using firestore

### ISSUE THREAD

**Issue by kkganesan** [GIfatahTH/states-rebuilder-examples#2]
Will be useful to have an example on firestore auth, crud workflow abstraction.
Similar to https://github.com/FilledStacks/flutter-tutorials/tree/master/039-firebase-custom-start-user-profile

**Comment by amoslai5128** [comment]
Yes, I do want to see Firebase example too!

**Comment by GIfatahTH** [comment]
I add an example for firebase sign in.
 https://github.com/GIfatahTH/states-rebuilder-examples/tree/master/008-clean_architecture_firebase_login

**Comment by amoslai5128** [comment]
> I add an example for firebase sign in.
> https://github.com/GIfatahTH/states-rebuilder-examples/tree/master/008-clean_architecture_firebase_login

You are the king!!!!
Can't wait for more

**Comment by amoslai5128** [comment]
> I add an example for firebase sign in.
> https://github.com/GIfatahTH/states-rebuilder-examples/tree/master/008-clean_architecture_firebase_login

May I request an example in Firebase Todo list? 
Many thanks
